// One-off generator for src/lib/quran/chapter-word-counts.ts — run with:
//   node --env-file=.env.local --import=tsx scripts/fetch-chapter-word-counts.ts
// Sums each chapter's word count (excluding end-of-ayah marker glyphs) from
// the same Quran Foundation Content API the app already uses, so the static
// table matches the mushaf data rather than an external source.
import { writeFileSync } from "node:fs";

import { quranFetch } from "@/lib/quran/client";

type VersesByChapterResponse = {
  verses: {
    words: { char_type_name: string }[];
  }[];
  pagination: { total_pages: number };
};

async function fetchChapterWordCount(chapterId: number): Promise<number> {
  let total = 0;
  let page = 1;
  let totalPages = 1;

  do {
    const data = await quranFetch<VersesByChapterResponse>(
      `/verses/by_chapter/${chapterId}`,
      { words: "true", word_fields: "char_type_name", per_page: 50, page },
      86400
    );
    for (const verse of data.verses) {
      total += verse.words.filter((w) => w.char_type_name !== "end").length;
    }
    totalPages = data.pagination.total_pages;
    page += 1;
  } while (page <= totalPages);

  return total;
}

async function main() {
  const counts: Record<number, number> = {};
  for (let chapterId = 1; chapterId <= 114; chapterId++) {
    counts[chapterId] = await fetchChapterWordCount(chapterId);
    process.stderr.write(`${chapterId}: ${counts[chapterId]}\n`);
  }

  const body = [
    "// Generated by scripts/fetch-chapter-word-counts.ts — do not edit by hand.",
    "// Word count per sourate (excluding end-of-ayah marker glyphs), sourced from",
    "// the Quran Foundation Content API. Used to weight aggregate memorization",
    "// progress by content volume rather than raw verse count, since verse length",
    "// varies a lot across sourates.",
    "export const CHAPTER_WORD_COUNTS: Record<number, number> = {",
    ...Array.from({ length: 114 }, (_, i) => i + 1).map(
      (id) => `  ${id}: ${counts[id]},`
    ),
    "};",
    "",
  ].join("\n");

  writeFileSync("src/lib/quran/chapter-word-counts.ts", body);
}

main();
